name: Rust CI Linux

on:
  workflow_dispatch:
  push:
    branches:
      - ci
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Tauri build
      run: |
        sudo apt update
        sudo apt install -y libwebkit2gtk-4.1-dev
        pnpm install
        pnpm tauri icon
        NO_STRIP=1 pnpm tauri build --no-bundle
        pnpm tauri bundle --bundles deb
    - name: Upload Debian artifact
      uses: actions/upload-artifact@v4
      with:
        name: zcash-vote-audit.deb
        path: src-tauri/target/release/bundle/deb/*.deb
    - name: Create Release
      if: startsWith(github.ref_name, 'v')
      uses: softprops/action-gh-release@v2
      with:
        files: src-tauri/target/release/bundle/deb/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
